# Generated by Django 5.1.3 on 2024-12-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondName',
        ),
    ]
